### ISSUE TITLE
Cannot run with sound null safety,

### ISSUE THREAD

**Issue by Sagarsappic** [KasemJaffer/flutter_absolute_path#19]
Waiting for version for null safety..........

**Comment by Sagarsappic** [comment]
Please upgrade this version to support null safety

**Comment by pranoy-smarthealth** [comment]
Please upgrade it to support null safety
Cant run with null safety please upgrade this version to null safety
The plugins  flutter_absolute_path` use a deprecated version of the Android embedding.
To avoid unexpected runtime failures, or future build failures, try to see if these plugins support the Android V2 embedding. Otherwise, consider removing them since a future release of Flutter will remove these deprecated APIs.

**Comment by mkwsra** [comment]
use this version if you wish

Do it like so in your pubspe.yaml:

```yaml
flutter_absolute_path:
    git:
      url: https://github.com/multicaret/flutter_absolute_path
```
