### ISSUE TITLE
Cannot run with sound null safety

### ISSUE THREAD

**Issue by omarnaser1997lucid** [KasemJaffer/flutter_absolute_path#22]

**Comment by mkwsra** [comment]
use this version if you wish

Do it like so in your pubspe.yaml:

```yaml
flutter_absolute_path:
    git:
      url: https://github.com/multicaret/flutter_absolute_path
```
